env:
  global:
  - GH_REF: github.com/OSMBuildings/OSMBuildings.git
  - secure: "sAp3gwhczJugVc2nh6qbbWgPs0Z23zJ86hyA0q7UR7KC25YXi9vFWExhYDh4WRcDTT3EVNES14RVTsJA9Pz5lmYFWy580q+OjUAfQtcdoXsTw2SeDvKyTxdqMCmFSzxpl/nmoA+CuUbrqAPr/r6uq6y80YArU7VGTZujbUR4+C0znjYoReB61aLLLysLI8ozHhOpEM5f7Qembw+RBNa6tMkkojeqP6iIfbqFQ+lpWtxofGyeLVcHsYBv7AS3SOFSOc5S1RFWTQ7mwBaF5uDtWt3nmeG+tnkVLRoEoEO/wOSXW8u1J7W7hHCFz6Ru8bMY1EoM6k/S0wzG+qqwlX527OnDttwfjpjIogRgqoIJEIL1zATELtD5w5kMtMFpb0aDdDTSVKTKhRwFYErp3qvxNZMoDpwCV4m4fDRC0hHWF8OlxXqAurq9JIrNC/WExOQI/ZdPkYrFBzurAu1oRgJ+fUcSFVx/7sPVVI4Us1w4K3JvF70/xD4I/dRpOpQlhARn86p8JktUSCzQspNrQXDMg43Rmxa8RFt6w8wzypJgJQUUxm3yqwp659JG/80H4Gw+E+n2iepp4idrGOHeAUv18W9ZFqDRdcPCQ4gdjpCvpt0mzoJmCJBelhiY0HpcgwVZUiSQl/7S28wFCh7E3IuAQW0ZAqIU8s032B7Vj98jigw="

language: node_js
node_js:
- "0.10"
before_script:
  - npm install grunt-cli -g
  - npm install
script:
  - grunt release
